### ISSUE TITLE
美团

### ISSUE THREAD

**Issue by girlskk** [Giyn/PythonScraper#1]
你好，很抱歉未经您的允许尝试了一下您的代码，再使用您的代码的时候，爬虫每次都是使用一个专门的Google浏览器打开，不是使用我本机上的Google浏览器，因为我更改默认的搜索引擎是无效的，因为每次都会打开一个新的Google，但是无论我是否科学上网，都是无法正常运行爬虫的，不知道是因为美团跳出来的登陆验证还是网络原因，您能帮我解决一下吗？谢谢！！！

**Comment by Giyn** [comment]
您好，我在GitHub更新了代码，在第28行增添了 option.add_argument("--disable-blink-features=AutomationControlled")
您可以下载最新的 88 版本 chromewebdriver，并重新运行代码，若有其他问题出现，可以继续讨论~



giyn.jy@gmail.com
 
发件人： Tayloran
发送时间： 2021-02-28 21:57
收件人： Giyn/PythonScraper
抄送： Subscribed
主题： [Giyn/PythonScraper] 美团 (#1)
你好，很抱歉未经您的允许尝试了一下您的代码，再使用您的代码的时候，爬虫每次都是使用一个专门的Google浏览器打开，不是使用我本机上的Google浏览器，因为我更改默认的搜索引擎是无效的，因为每次都会打开一个新的Google，但是无论我是否科学上网，都是无法正常运行爬虫的，不知道是因为美团跳出来的登陆验证还是网络原因，您能帮我解决一下吗？谢谢！！！

**Comment by girlskk** [comment]
感谢您的回复！ 您好，我按照您的回复添加了代码，chromewebdriver的版本也是88版的，再次运行之后还是会跳出登陆页面，需要我手动登录，登陆后然后还是没有爬取成功，但是错误类型变了，我在下面附上运行后的提示。

DevTools listening on ws://127.0.0.1:56292/devtools/browser/d0df600f-a9f1-476f-837f-ae1bf107e96f
2021-03-01 10:53:49,830 - INFO: scraping https://gz.meituan.com/meishi/b1184/pn1/
[14148:17988:0301/105351.728:ERROR:device_event_log_impl.cc(211)] [10:53:51.728] USB: usb_device_han
dle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F
)
[14148:17988:0301/105351.756:ERROR:device_event_log_impl.cc(211)] [10:53:51.756] Bluetooth: bluetoot
h_adapter_winrt.cc:1203 Getting Radio failed. Chrome will be unable to change the power state by its
elf.
[14148:17988:0301/105351.782:ERROR:device_event_log_impl.cc(211)] [10:53:51.782] Bluetooth: bluetoot
h_adapter_winrt.cc:1296 OnPoweredRadiosEnumerated(), Number of Powered Radios: 0
[8456:10412:0301/105403.957:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL
 error code 1, net_error -200
2021-03-01 10:54:04,840 - INFO: scraping https://www.meituan.com/meishi/1464655070/
[8456:10412:0301/105407.337:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL
 error code 1, net_error -200
Traceback (most recent call last):
  File "college_town_food.py", line 195, in <module>
    save_to_MongoDB(detail_data)
  File "college_town_food.py", line 181, in save_to_MongoDB
    collection.update_one({
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\collection.py", line 1
019, in update_one
    self._update_retryable(
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\collection.py", line 8
68, in _update_retryable
    return self.__database.client._retryable_write(
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1497, in _retryable_write
    with self._tmp_session(session) as s:
  File "D:\Program Files (x86)\Anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1829, in _tmp_session
    s = self._ensure_session(session)
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1766, in __start_session
    server_session = self._get_server_session()
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1802, in _get_server_session
    return self._topology.get_server_session()
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\topology.py", line 485
, in get_server_session
    self._select_servers_loop(
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\topology.py", line 215
, in _select_servers_loop
    raise ServerSelectionTimeoutError(pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法接。,Timeout:30s,TopologyDescription<TopologyDescriptionid:603c573dd4ecb7cf0a364a0a,topology_type: Single, servers: [<ServerDescription ('localhost',27017)server_type:Unknown,rtt:None, error=AutoReconnect('localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')>]>

再次表示感谢.

**Comment by girlskk** [comment]
> 
> 您好，我在GitHub更新了代码，在第28行增添了 option.add_argument("--disable-blink-features=AutomationControlled") 您可以下载最新的 88 版本 chromewebdriver，并重新运行代码，若有其他问题出现，可以继续讨论~ giyn.jy@gmail.com 发件人： Tayloran 发送时间： 2021-02-28 21:57 收件人： Giyn/PythonScraper 抄送： Subscribed 主题： [Giyn/PythonScraper] 美团 ( [#1 ](https://github.com/Giyn/PythonScraper/issues/1)) 你好，很抱歉未经您的允许尝试了一下您的代码，再使用您的代码的时候，爬虫每次都是使用一个专门的Google浏览器打开，不是使用我本机上的Google浏览器，因为我更改默认的搜索引擎是无效的，因为每次都会打开一个新的Google，但是无论我是否科学上网，都是无法正常运行爬虫的，不知道是因为美团跳出来的登陆验证还是网络原因，您能帮我解决一下吗？谢谢！！！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢您的回复！ 您好，我按照您的回复添加了代码，chromewebdriver的版本也是88版的，再次运行之后还是会跳出登陆页面，需要我手动登录，登陆后然后还是没有爬取成功，但是错误类型变了，我在下面附上运行后的提示。

在ws：//127.0.0.1：56292 / devtools / browser / d0df600f-a9f1-476f-837f-ae1bf107e96f上监听的DevTools
2021-03-01 10：53：49,830-信息：抓取 https://gz.meituan.com/meishi/b1184/pn1/
[14148：17988：0301 / 105351.728：ERROR：device_event_log_impl.cc（211）] [10：53：51.728] USB：usb_device_han
dle_win.cc:1049无法从节点连接中读取描述符：连到系统上的设备没有发挥作用。（0x1F
）
[14148：17988：0301 / 105351.756：ERROR：device_event_log_impl.cc（211）] [10：53：51.756]蓝牙：bluetoot
h_adapter_winrt.cc:1203获取广播失败。 Chrome将无法通过其更改电源状态
小精灵。
[14148：17988：0301 / 105351.782：ERROR：device_event_log_impl.cc（211）] [10：53：51.782]蓝牙：bluetoot
h_adapter_winrt.cc:1296 OnPoweredRadiosEnumerated（），有源无线电的数量：0
[8456：10412：0301 / 105403.957：​​ERROR：ssl_client_socket_impl.cc（962）]握手失败； 返回-1，SSL
错误代码1，net_error -200
2021-03-01 10：54：04,840-信息：抓取 https://www.meituan.com/meishi/1464655070/
[8456：10412：0301 / 105407.337：ERROR：ssl_client_socket_impl.cc（962）]握手失败； 返回-1，SSL
错误代码1，net_error -200
追溯（最近一次通话）：
在第195行的文件“ college_town_food.py”中
save_to_MongoDB（详细数据）
在save_to_MongoDB中的文件“ college_town_food.py”，第181行
collection.update_one（{
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ collection.py”，第1行
019，位于update_one中
self._update_retryable（
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ collection.py”，第8行
68，在_update_retryable中
返回self .__ database.client._retryable_write（
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ mongo_client.py”，行
1497，在_retryable_write中
与self._tmp_session（session）为s：
输入文件“ D：\ Program Files（x86）\ Anaconda3 \ lib \ contextlib.py”，在第113行中 输入
返回next（self.gen）
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ mongo_client.py”，行
1829年，在_tmp_session中
s = self._ensure_session（会话）
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ mongo_client.py”，行
1816，在_ensure_session中
返回self .__ start_session（真，causal_consistency = False）
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ mongo_client.py”，行
1766年，在__start_session中
server_session = self._get_server_session（）
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ mongo_client.py”，行
1802，在_get_server_session中
返回self._topology.get_server_session（）
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ topology.py”，第485行
，在get_server_session中
self._select_servers_loop（
文件“ D：\ firefox \ python \ PythonScraper-master \ venv \ lib \ site-packages \ pymongo \ topology.py”，第215行
，位于_select_servers_loop中
引发ServerSelectionTimeoutError（pymongo.errors.ServerSelectionTimeoutError：localhost：27017：[WinError 10061]由于目标计算机积极拒绝，无法接听。 ，27017）server_type：Unknown，rtt：None，error = AutoReconnect（'localhost：27017：[WinError 10061]由于目标计算机积极拒绝，无法连接。']>]>

再次表示感谢.

**Comment by girlskk** [comment]
> 
> 您好，我在GitHub更新了代码，在第28行增添了 option.add_argument("--disable-blink-features=AutomationControlled") 您可以下载最新的 88 版本 chromewebdriver，并重新运行代码，若有其他问题出现，可以继续讨论~ giyn.jy@gmail.com 发件人： Tayloran 发送时间： 2021-02-28 21:57 收件人： Giyn/PythonScraper 抄送： Subscribed 主题： [Giyn/PythonScraper] 美团 (#1) 你好，很抱歉未经您的允许尝试了一下您的代码，再使用您的代码的时候，爬虫每次都是使用一个专门的Google浏览器打开，不是使用我本机上的Google浏览器，因为我更改默认的搜索引擎是无效的，因为每次都会打开一个新的Google，但是无论我是否科学上网，都是无法正常运行爬虫的，不知道是因为美团跳出来的登陆验证还是网络原因，您能帮我解决一下吗？谢谢！！！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢您的回复！ 您好，我按照您的回复添加了代码，chromewebdriver的版本也是88版的，再次运行之后还是会跳出登陆页面，需要我手动登录，登陆后然后还是没有爬取成功，但是错误类型变了，我在下面附上运行后的提示。

DevTools listening on ws://127.0.0.1:56292/devtools/browser/d0df600f-a9f1-476f-837f-ae1bf107e96f
2021-03-01 10:53:49,830 - INFO: scraping https://gz.meituan.com/meishi/b1184/pn1/
[14148:17988:0301/105351.728:ERROR:device_event_log_impl.cc(211)] [10:53:51.728] USB: usb_device_han
dle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F
)
[14148:17988:0301/105351.756:ERROR:device_event_log_impl.cc(211)] [10:53:51.756] Bluetooth: bluetoot
h_adapter_winrt.cc:1203 Getting Radio failed. Chrome will be unable to change the power state by its
elf.
[14148:17988:0301/105351.782:ERROR:device_event_log_impl.cc(211)] [10:53:51.782] Bluetooth: bluetoot
h_adapter_winrt.cc:1296 OnPoweredRadiosEnumerated(), Number of Powered Radios: 0
[8456:10412:0301/105403.957:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL
 error code 1, net_error -200
2021-03-01 10:54:04,840 - INFO: scraping https://www.meituan.com/meishi/1464655070/
[8456:10412:0301/105407.337:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL
 error code 1, net_error -200
Traceback (most recent call last):
  File "college_town_food.py", line 195, in <module>
    save_to_MongoDB(detail_data)
  File "college_town_food.py", line 181, in save_to_MongoDB
    collection.update_one({
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\collection.py", line 1
019, in update_one
    self._update_retryable(
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\collection.py", line 8
68, in _update_retryable
    return self.__database.client._retryable_write(
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1497, in _retryable_write
    with self._tmp_session(session) as s:
  File "D:\Program Files (x86)\Anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1829, in _tmp_session
    s = self._ensure_session(session)
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1766, in __start_session
    server_session = self._get_server_session()
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py", line
 1802, in _get_server_session
    return self._topology.get_server_session()
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\topology.py", line 485
, in get_server_session
    self._select_servers_loop(
  File "D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\topology.py", line 215
, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] 由于目标计算机积极拒绝
，无法连接。, Timeout: 30s, Topology Description: <TopologyDescription id: 603c573dd4ecb7cf0a364a0a,
 topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt:
 None, error=AutoReconnect('localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')>]
>

再次感谢您的回复

**Comment by girlskk** [comment]
你好，这里应该也可以联系到吧，我在GitHub上回复您了，再次在此发一下新的问题

DevTools listening on ws://
127.0.0.1:56292/devtools/browser/d0df600f-a9f1-476f-837f-ae1bf107e96f
2021-03-01 10:53:49,830 - INFO: scraping
https://gz.meituan.com/meishi/b1184/pn1/
[14148:17988:0301/105351.728:ERROR:device_event_log_impl.cc(211)]
[10:53:51.728] USB: usb_device_han
dle_win.cc:1049 Failed to read descriptor from node connection:
连到系统上的设备没有发挥作用。 (0x1F
)
[14148:17988:0301/105351.756:ERROR:device_event_log_impl.cc(211)]
[10:53:51.756] Bluetooth: bluetoot
h_adapter_winrt.cc:1203 Getting Radio failed. Chrome will be unable to
change the power state by its
elf.
[14148:17988:0301/105351.782:ERROR:device_event_log_impl.cc(211)]
[10:53:51.782] Bluetooth: bluetoot
h_adapter_winrt.cc:1296 OnPoweredRadiosEnumerated(), Number of Powered
Radios: 0
[8456:10412:0301/105403.957:ERROR:ssl_client_socket_impl.cc(962)] handshake
failed; returned -1, SSL
error code 1, net_error -200
2021-03-01 10:54:04,840 - INFO: scraping
https://www.meituan.com/meishi/1464655070/
[8456:10412:0301/105407.337:ERROR:ssl_client_socket_impl.cc(962)] handshake
failed; returned -1, SSL
error code 1, net_error -200
Traceback (most recent call last):
File "college_town_food.py", line 195, in
save_to_MongoDB(detail_data)
File "college_town_food.py", line 181, in save_to_MongoDB
collection.update_one({
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\collection.py",
line 1
019, in update_one
self._update_retryable(
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\collection.py",
line 8
68, in _update_retryable
return self.__database.client._retryable_write(
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py",
line
1497, in _retryable_write
with self._tmp_session(session) as s:
File "D:\Program Files (x86)\Anaconda3\lib\contextlib.py", line 113, in
*enter*
return next(self.gen)
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py",
line
1829, in _tmp_session
s = self._ensure_session(session)
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py",
line
1816, in _ensure_session
return self.__start_session(True, causal_consistency=False)
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py",
line
1766, in __start_session
server_session = self._get_server_session()
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\mongo_client.py",
line
1802, in _get_server_session
return self._topology.get_server_session()
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\topology.py",
line 485
, in get_server_session
self._select_servers_loop(
File
"D:\firefox\python\PythonScraper-master\venv\lib\site-packages\pymongo\topology.py",
line 215
, in _select_servers_loop
raise
ServerSelectionTimeoutError(pymongo.errors.ServerSelectionTimeoutError:
localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。, Timeout: 30s, Topology
Description: <TopologyDescription id:
603c573dd4ecb7cf0a364a0a,topology_type: Single, servers:
[<ServerDescription ('localhost', 27017) server_type: Unknown, rtt:None,
error=AutoReconnect('localhost:27017: [WinError 10061]
由于目标计算机积极拒绝，无法连接。')>]

期待您的回复，谢谢啦

Jiyuan Xu <notifications@github.com> 于2021年2月28日周日 下午10:47写道：

**Comment by Giyn** [comment]
跑了一下代码，发现的确存在一些问题，我这几天修改一下代码~

**Comment by girlskk** [comment]
嗯嗯，好的，可能是美团的反爬更新了，无法跳过登陆页面，加油！！！

Jiyuan Xu <notifications@github.com> 于2021年3月1日周一 下午7:20写道：

**Comment by Giyn** [comment]
61 ~ 66 行我增添了几行代码，你写入自己的手机号和密码试试看能不能登录，如果能登录进去就可以了~



giyn.jy@gmail.com
 
发件人： Tayloran
发送时间： 2021-03-01 20:17
收件人： Giyn/PythonScraper
抄送： Jiyuan Xu; Comment
主题： Re: [Giyn/PythonScraper] 美团 (#1)
嗯嗯，好的，可能是美团的反爬更新了，无法跳过登陆页面，加油！！！ 

Jiyuan Xu <notifications@github.com> 于2021年3月1日周一 下午7:20写道：

**Comment by girlskk** [comment]
感谢您的修改，这次确实可以登录了，但是会验证手机号哎，然后输完验证码登陆成功之后，程序还是运行失败，不会爬到数据

Jiyuan Xu <notifications@github.com> 于2021年3月1日周一 下午8:24写道：

**Comment by Giyn** [comment]
你可以先试着在Chrome浏览器中手动登录一下美团，然后再重新运行程序，我当时是这么解决的，如果仍然需要验证，那可能需要用到appium这个工具，我后续可以继续改进代码。



giyn.jy@gmail.com
 
发件人： Tayloran
发送时间： 2021-03-02 19:15
收件人： Giyn/PythonScraper
抄送： Jiyuan Xu; Comment
主题： Re: [Giyn/PythonScraper] 美团 (#1)
感谢您的修改，这次确实可以登录了，但是会验证手机号哎，然后输完验证码登陆成功之后，程序还是运行失败，不会爬到数据 

Jiyuan Xu <notifications@github.com> 于2021年3月1日周一 下午8:24写道：

**Comment by Giyn** [comment]
另外我对代码的解析语句进行了改进，你可以更新一下代码~

**Comment by girlskk** [comment]
> 哇，大神厉害，果然可以爬啦，哈哈哈哈，虽然只能爬几条信息，嘿嘿，谢谢大佬指点。后续再做一个伪装就完成啦，这样简单的点击读取，几分钟就被美团识别了，哈哈哈，想要爬多一点数据还是要加代理池，厉害厉害，赞赞赞
> 
> 另外我对代码的解析语句进行了改进，你可以更新一下代码~

**Comment by Giyn** [comment]
嘿嘿，恭喜你 后面对代码如果有什么疑问欢迎提issue~

**Comment by girlskk** [comment]
> 多谢您的帮助啦，我才终于把这个项目运行成功。万分谢谢
> 
> 嘿嘿，恭喜你 后面对代码如果有什么疑问欢迎提issue~
